name: Build and Package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 安装 Linux 所需依赖
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev fakeroot dpkg-dev binutils

      # 设置图片扩展名（区分平台）
      - name: Set image extension on Linux/macOS
        if: runner.os != 'Windows'
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            echo "IMAGE_EXT=icns" >> $GITHUB_ENV
          else
            echo "IMAGE_EXT=png" >> $GITHUB_ENV
          fi

      - name: Set image extension on Windows
        if: runner.os == 'Windows'
        run: echo "IMAGE_EXT=ico" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build project
        run: |
          mvn clean package
          mvn javafx:jlink

      - name: Package application
        run: mvn org.panteleyev:jpackage-maven-plugin:jpackage -Dimage-extension=${{ env.IMAGE_EXT }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProjectManagement-${{ runner.os }}
          path: target/installer/
