name: Build and Package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 安装 Linux 所需的依赖
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y fakeroot binutils

      # 设置图标扩展名
      - name: Set Windows image extension
        if: runner.os == 'Windows'
        run: echo "image-extension=ico" >> $GITHUB_ENV

      - name: Set Linux image extension
        if: runner.os == 'Linux'
        run: echo "image-extension=png" >> $GITHUB_ENV

      - name: Set macOS image extension
        if: runner.os == 'macOS'
        run: echo "image-extension=icns" >> $GITHUB_ENV

      - name: Build with Maven
        run: |
          mvn clean package
          mvn javafx:jlink

      - name: Package application
        run: |
          # 使用完整的 Maven 插件目标语法
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mvn org.panteleyev:jpackage-maven-plugin:jpackage -Dimage-extension=${{ env.image-extension }} \
              -Djpackage.arguments="--win-menu,--win-dir-chooser"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            mvn org.panteleyev:jpackage-maven-plugin:jpackage -Dimage-extension=${{ env.image-extension }} \
              -Djpackage.arguments="--mac-package-identifier,com.example.projectmanagement,--mac-package-name,ProjectManagement,--mac-category,Business"
          else
            mvn org.panteleyev:jpackage-maven-plugin:jpackage -Dimage-extension=${{ env.image-extension }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProjectManagement-${{ runner.os }}
          path: target/installer/*