name: Build and Package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev fakeroot dpkg-dev binutils

      # 设置图标扩展名
      - name: Set Windows image extension
        if: runner.os == 'Windows'
        run: echo "image-extension=ico" >> $GITHUB_ENV

      - name: Set Linux image extension
        if: runner.os == 'Linux'
        run: echo "image-extension=png" >> $GITHUB_ENV

      - name: Set macOS image extension
        if: runner.os == 'macOS'
        run: echo "image-extension=icns" >> $GITHUB_ENV

      - name: Build project
        run: |
          mvn clean package
          mvn javafx:jlink

      - name: Package application
        run: mvn org.panteleyev:jpackage-maven-plugin:jpackage -Dimage-extension=${{ env.IMAGE_EXT }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProjectManagement-${{ runner.os }}
          path: target/installer/
